### PR TITLE
add missing matplotlib dependency for python3

### PR DESCRIPTION
**Pull request by huberya**

### CODE REVIEW

**Review by HannesSommer — APPROVED** [review]
Thanks. Looks good to me. But what is actually needing `matplotlib` in `sm_python`? I'm a bit surprised by this fat dependency.

**Comment by HannesSommer** [comment]
retest this please.

**Comment by huberya** [comment]
Ah did not see the update
Yes it is needed (kevin run into the problem initially) for example here:
https://github.com/ethz-asl/schweizer_messer/blob/master/sm_python/python/sm/PlotCollection.py

**Comment by HannesSommer** [comment]
retest this please

**Pull request merged**
